[workspace]
members = [
    "01_schotter", 
    "02_particles", 
    "03_flow_fields",
    "04_penrose_flake",
    "05_differential_growth",
    "06_differential_growth_vec",
    "07_edge_detection",
]
resolver="2"


