[package]
name = "penrose_flake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
palette = { version = "0.5", default-features = false, features = ["named"] }
